# Generated by Django 5.2.7 on 2025-11-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.IntegerField(default=1),
        ),
    ]
