# Generated by Django 5.2.7 on 2025-11-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_data', '0002_lesson_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
